### ISSUE TITLE
Property _ansible_debug in resource xADDomain is not a valid property

### ISSUE THREAD

**Issue by pyrotimux** [trondhindenes/Ansible-Auto-Generated-Modules#1]
Hello,

I am using the generated win_xaddomain module from here to get the active directory init, but I keep getting this error "Property _ansible_debug in resource xADDomain is not a valid property." I am on ansible 2.0.2.

Full error message:

```
TASK [Init Domain] *************************************************************
fatal: [10.255.10.20]: FAILED! => {"Attributes": ["DomainAdministratorCredential_password", "DomainAdministratorCredential_username", "DomainName", "DomainNetbiosName", "SafemodeAdministratorPassword_password", "SafemodeAdministratorPassword_username", "_ansible_check_mode", "_ansible_debug", "_ansible_diff", "_ansible_no_log", "_ansible_verbosity"], "DomainAdministratorCredential_password": "vagrant", "DomainAdministratorCredential_username": "vagrant", "DomainName": "dc01.testrealm.com", "DomainNetbiosName": "dc01", "SafemodeAdministratorPassword_password": "vagrant", "SafemodeAdministratorPassword_username": "vagrant", "changed": false, "failed": true, "msg": "Property _ansible_debug in resource xADDomain is not a valid property", "resource_name": "xADDomain"}
```

Playbook:

``` yaml

---
- hosts: ps_main
  gather_facts: false
  tasks:
  - name: Make sure the LCM refresh mode is disabled
    win_lcm5:
      refresh_mode: "Disabled"
    tags:
      - Config
  - name: Download required Packages
    win_oneget:
      name: "xActiveDirectory"
    tags:
      - Oneget
  - name: Install ADDS and RSAT
    win_feature: 
      name: "AD-Domain-Services,RSAT-AD-Tools"
    tags:
      - WindowsFeature
  - name: Init Domain
    win_xaddomain:
      DomainName: "dc01.testrealm.com"
      DomainNetbiosName: "dc01"
      DomainAdministratorCredential_username: "vagrant"
      DomainAdministratorCredential_password: "vagrant"
      SafemodeAdministratorPassword_username: "vagrant"
      SafemodeAdministratorPassword_password: "vagrant"
    tags:
      - DomainInit
  - name: Wait for domain
    win_ad_xwaitfordomain:
      DomainUserCredential_username: "vagrant"
      DomainUserCredential_password: "vagrant"
      RetryCount: 20
      RetryIntervalSec: 30
  - name: Add Users
    win_xaduser:
      DomainName: "dc01.testrealm.com"
      DomainAdministratorCredential_username: "vagrant"
      DomainAdministratorCredential_password: "vagrant"
      UserName: "ichiban"
      Password_username: "ichiban"
      Password_password: "ichiP@ssw0rd"
    tags:
      - AddUsers
```

Thanks for your help!!
