### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by SuperMarioo** [trondhindenes/Ansible-Auto-Generated-Modules#2]
Hi trondhindenes , 

Nice to see DSC Ansible integration ! :+1: really cool staff !! 
I'm new to Ansible and I'm having some issues when I  use win_xtimezone module with Ansible and i'm not sure if my playbook is right .
- name: TimeZone Setup
  hosts: all
  gather_facts: false
  tasks:
  - name: Setting Up Time Zone
    win_xtimezone:
      TimeZone:Central European Summer Time
      IsSingleInstance:yes

I keep getting errors .

ERROR! this task 'win_xtimezone' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

I would appreciate any help :)

Regards 

Mariusz

**Comment by trondhindenes** [comment]
Hi, Thanks!
Could you send me the actual code of the playbook you're struggling with?

**Comment by SuperMarioo** [comment]
HI ,

```
- name: TimZone Setup
  hosts: all
  tasks:
    - name: Setting Up Time Zone
      win_xtimezone:
        TimeZone:Central European Summer Time
        IsSingleInstance:yes
```

That's the playbook , I'm just trying to test some of the converted DSC Resources .

**Comment by trondhindenes** [comment]
hm, there's no reason why that shouldn't work. Which version of PowerShell and Ansible are you on?

**Comment by SuperMarioo** [comment]
Anisble 2.1.0.0 , PowerShell 5 RTM . But it looks like there is some issue with the playbook , 

`ERROR! this task 'win_xtimezone' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/home/Azure_Admin/ansible_test/jazda.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Setting Up Time Zone
      ^ here

The error appears to have been in '/home/Azure_Admin/ansible_test/jazda.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Setting Up Time Zone
      ^ here
`

**Comment by trondhindenes** [comment]
I will have a look today or tomorrow!

**Comment by SuperMarioo** [comment]
Cheers !!!

**Comment by trondhindenes** [comment]
Sorry, haven't gotten around to look at this yet. Will do so during the weekend.

**Comment by SuperMarioo** [comment]
Cool

**Comment by trondhindenes** [comment]
So, there's obviously something wrong with the xdscdomainjoin module, since it's not loading. I would recommend that you use the win_xcomputer resource instead:

``` yaml
    - name: Join to domain
      win_xcomputer:
        credential_password: administrator
        Credential_username: mypassword
        DomainName: mydomain.com
        AutoInstallModule: yes
```
